version: '3.2'
services:
  app:
    build:
      context: .
      args:
        _WP_DB_HOST: "127.0.0.1"
        _WP_DB_USER: reasonablefaith
        _WP_DB_NAME: reasonablefaith_wp
        _WP_DB_PASSWORD: <insert_password_here>
        _WP_THEMES: https://storage.googleapis.com/reasonablefaith-public/reasonablefaith.zip
        _WP_PLUGINS: classic-editor pagemash yet-another-featured-posts-plugin wp-stateless wordpress-importer wp-mail-smtp https://storage.googleapis.com/reasonablefaith-public/wp-orderposts.zip
        _CLOUDSQL_INSTANCE: "dolcestrings:australia-southeast1:mysql"
        _SERVICE_ACCOUNT_FILE: service-account.json
    environment: 
      PORT: 3000
    ports:
      - 3000:3000
    restart: always